# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/154632e5-40d5-43fc-af60-99f29099e9e7";
      fsType = "ext4";
    };

  fileSystems."/bin" =
    { device = "/usr/bin";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fba97cf9-9f6e-41a3-95ee-954da238fa5d";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9961-628C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/var/lib/docker/overlay2/730edcd0fbdecee989bded2769dc98d03b8dc84138c357f9c4f4602823ae7729/merged" =
  #   { device = "overlay";
  #     fsType = "overlay";
  #   };

  # fileSystems."/var/lib/docker/overlay2/1fa90526e1cdc07d5914004d8d18611356b5291010808c4d68b7e43d973a7818/merged" =
  #   { device = "overlay";
  #     fsType = "overlay";
  #   };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-041cf1b9aa1f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-5c1b929d2062.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-91eea58b065e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-a7453282d4f9.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-cd281a4e028d.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6d20bc2.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf952057.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0-mullvad.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
